spring.application.name=store

# Connexion MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}



# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# Désactivation de Flyway pour éviter l'erreur MySQL 9.6
spring.flyway.enabled=false


logging.level.org.springframework.security=DEBUG
# JWT configuration
# Note: In a real application, you should store the secret key securely and not hard-code it in your properties file.
# the secret key should be at least 256 bits et n'erit pas le secret ici on utilise une variable d'environnement 
spring.jwt.secret=${JWT_SECRET_KEY}
Stripe.secretKey =${STRIPE_SECRET_KEY}
Stripe.webhookSecretKey=${STRIPE_WEBHOOK_SECRET_KEY}

# 5 minutes in seconds
Spring.Jwt.expiration=7200
# 7 days in milliseconds
Spring.jwt.refreshExpiration=604800


websitUrl = http://localhost:4200